version: '3.9'

services:
  agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always

networks:
  default:
    name: my-main-net
    external: true
