version: '3.9'

services:
  guacamole:
    container_name: guacamole
    image: jwetzell/guacamole:latest
    volumes:
      - ./postgres:/config
    ports:
      - 8080:8080
    restart: unless-stopped
    
volumes:
  postgres:
    driver: local

networks:
  default:
    name: my-main-net
    external: true